version: '3.8'

services:
  json-schema-builder:
    # Builds the image using the Dockerfile in the current directory
    build: .
    container_name: json-schema-builder-web
    restart: unless-stopped
    networks:
      - app

# Use the command to create an external network called 'app' before starting the containers:
# docker network create app
networks:
  app:
    external: true